spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0 #this is for number of calls to be traced
server:
  port: 8100

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
