spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      discovery:
#        locator:
##          enabled: true
##          lower-case-service-id: true
  sleuth:
    sampler:
      probability: 1.0 #this is for number of calls to be traced

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka